### ISSUE TITLE
t/01-basic.t fails (with Stenciller 1.302?)

### ISSUE THREAD

**Issue by eserte** [Csson/p5-Dist-Zilla-Plugin-Stenciller-HtmlExamples#1]
See http://analysis.cpantesters.org/reports_by_field?distv=Dist-Zilla-Plugin-Stenciller-HtmlExamples-0.0101;field=mod%3AStenciller for a list of test reports with the corresponding installed Stenciller version. With 1.302 it always fails, with 1.301 it is mostly passes.

**Comment by Csson** [comment]
Hi!

This should be fixed in 0.0102.

/Erik
